Update dash-example.cc
Corrected the error for ns-3 which was:

link-example.cc:171:24: error: variable length array of non-POD element type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >')
  std::string protocols[users];